# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  taskmanagmentcoreapi:
    image: taskmanagmentcoreapi
    build:
      context: .
      dockerfile: TaskManagmentCore.Api/Dockerfile
    ports:
      - 5000:5000
  
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: renato123
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-volume:
    driver: local

